// The MCP server binary. All domain logic (search, bundle listing, frontmatter)
// lives in the library crate (src/lib.rs and its modules) — this file only
// wires that logic to the MCP protocol: tool definitions, resource handlers,
// and the stdio transport.

use anyhow::Result;
use mcp_server::bundle::{knowledge_dir, list_docs_in};
use mcp_server::frontmatter::extract_frontmatter_field;
use mcp_server::search::search_docs_in;
use rmcp::{
    // MCP SDK types: error type, server trait, service wiring, tool routing machinery,
    // parameter wrapper, all protocol model types, JSON schema + serde derives,
    // the #[tool] / #[tool_router] / #[tool_handler] macros, and stdio transport
    ErrorData as McpError,
    RoleServer,
    ServerHandler,
    ServiceExt,
    handler::server::router::tool::ToolRouter,
    handler::server::wrapper::Parameters,
    model::*,
    schemars,
    serde,
    service::RequestContext,
    tool,
    tool_handler,
    tool_router,
    transport::stdio,
};

// The input schema for the search_docs tool.
// #[derive] generates the Debug, Deserialize, and JsonSchema implementations
// automatically — equivalent to Lombok @Data + Jackson annotations in Java.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
struct SearchInput {
    /// Search term to look up in the KUKA documentation
    query: String,
}

// The MCP server struct. The tool_router field is generated by the #[tool_router]
// macro and holds the dispatch table that routes incoming tool calls to the
// correct method. #[allow(dead_code)] silences the compiler warning about the
// field never being read directly.
#[derive(Clone)]
struct KukaServer {
    #[allow(dead_code)]
    tool_router: ToolRouter<KukaServer>,
}

// #[tool_router] scans this impl block for methods marked #[tool] and wires them
// into the MCP protocol automatically — generating the tool list and dispatch logic.
#[tool_router]
impl KukaServer {
    fn new() -> Self {
        Self {
            tool_router: Self::tool_router(),
        }
    }

    // Lightweight health-check tool. Useful for verifying the server is reachable
    // before sending real queries.
    #[tool(description = "Ping the KUKA knowledge server to confirm it is running")]
    fn ping(&self) -> Result<CallToolResult, McpError> {
        Ok(CallToolResult::success(vec![Content::text(
            "KUKA Knowledge server is online and ready.",
        )]))
    }

    #[tool(description = "List all documents in the KUKA knowledge bundle, grouped by type")]
    fn list_docs(&self) -> Result<CallToolResult, McpError> {
        list_docs_in(&knowledge_dir())
    }

    #[tool(description = "Search KUKA robot documentation for a given query")]
    fn search_docs(
        &self,
        Parameters(input): Parameters<SearchInput>,
    ) -> Result<CallToolResult, McpError> {
        search_docs_in(&knowledge_dir(), input.query)
    }
}

// #[tool_handler] wires the tool_router into the ServerHandler trait so the MCP
// framework knows how to dispatch incoming tool calls.
#[tool_handler]
impl ServerHandler for KukaServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(
            ServerCapabilities::builder()
                .enable_tools()
                .enable_resources()
                .build(),
        )
        .with_instructions(
            "KUKA AMR robot knowledge server. \
             Use the ping tool to confirm the server is alive."
                .to_string(),
        )
    }

    async fn list_resources(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListResourcesResult, McpError> {
        let knowledge_dir = knowledge_dir();
        let mut resources: Vec<Resource> = Vec::new();

        if let Ok(entries) = std::fs::read_dir(&knowledge_dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.extension().and_then(|e| e.to_str()) != Some("md") {
                    continue;
                }
                if let Ok(content) = std::fs::read_to_string(&path) {
                    let stem = path.file_stem().unwrap().to_string_lossy().to_string();
                    let title = extract_frontmatter_field(&content, "title")
                        .unwrap_or_else(|| stem.clone());
                    let description = extract_frontmatter_field(&content, "description");
                    let uri = format!("kuka://docs/{stem}");

                    let mut raw = RawResource::new(uri, stem)
                        .with_title(title)
                        .with_mime_type("text/markdown".to_string());
                    if let Some(desc) = description {
                        raw = raw.with_description(desc);
                    }
                    resources.push(Annotated::new(raw, None));
                }
            }
        }

        Ok(ListResourcesResult::with_all_items(resources))
    }

    async fn read_resource(
        &self,
        request: ReadResourceRequestParams,
        _context: RequestContext<RoleServer>,
    ) -> Result<ReadResourceResult, McpError> {
        let uri = &request.uri;

        // Strip the kuka://docs/ prefix to recover the file stem
        let stem = uri.strip_prefix("kuka://docs/").ok_or_else(|| McpError {
            code: ErrorCode::RESOURCE_NOT_FOUND,
            message: format!("Unknown resource URI: {uri}").into(),
            data: None,
        })?;

        let path = knowledge_dir().join(format!("{stem}.md"));
        let content = std::fs::read_to_string(&path).map_err(|_| McpError {
            code: ErrorCode::RESOURCE_NOT_FOUND,
            message: format!("Resource not found: {uri}").into(),
            data: None,
        })?;

        Ok(ReadResourceResult::new(vec![ResourceContents::text(
            content,
            uri.clone(),
        )]))
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    // Send tracing output to stderr so it doesn't mix with MCP's stdout messages.
    // Log level is controlled by the RUST_LOG environment variable at runtime.
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::EnvFilter::from_default_env())
        .with_writer(std::io::stderr)
        .with_ansi(false) // disable colour codes (they corrupt MCP's JSON stream)
        .init();

    tracing::info!("Starting KUKA MCP server");

    // Attach the server to stdin/stdout and block until the client disconnects
    let service = KukaServer::new().serve(stdio()).await?;
    service.waiting().await?;
    Ok(())
}
