// The MCP server binary. All domain logic (search, bundle listing, frontmatter)
// lives in the library crate (src/lib.rs and its modules) — this file only
// wires that logic to the MCP protocol: tool definitions, resource handlers,
// and the stdio transport.

use anyhow::Result;
use mcp_server::bundle::{knowledge_dir, list_docs_in, load_bundle, resource_stem_is_safe};
use mcp_server::search::{SearchHit, parse_query, search};
use rmcp::{
    // MCP SDK types: error type, server trait, service wiring, tool routing machinery,
    // parameter wrapper, all protocol model types, JSON schema + serde derives,
    // the #[tool] / #[tool_router] / #[tool_handler] macros, and stdio transport
    ErrorData as McpError,
    RoleServer,
    ServerHandler,
    ServiceExt,
    handler::server::router::tool::ToolRouter,
    handler::server::wrapper::Parameters,
    model::*,
    schemars,
    serde,
    service::RequestContext,
    tool,
    tool_handler,
    tool_router,
    transport::stdio,
};

// The input schema for the search_docs tool.
// #[derive] generates the Debug, Deserialize, and JsonSchema implementations
// automatically — equivalent to Lombok @Data + Jackson annotations in Java.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
struct SearchInput {
    /// Search term to look up in the KUKA documentation
    query: String,
}

// The MCP server struct. The tool_router field is generated by the #[tool_router]
// macro and holds the dispatch table that routes incoming tool calls to the
// correct method. #[allow(dead_code)] silences the compiler warning about the
// field never being read directly.
#[derive(Clone)]
struct KukaServer {
    #[allow(dead_code)]
    tool_router: ToolRouter<KukaServer>,
}

// #[tool_router] scans this impl block for methods marked #[tool] and wires them
// into the MCP protocol automatically — generating the tool list and dispatch logic.
#[tool_router]
impl KukaServer {
    fn new() -> Self {
        Self {
            tool_router: Self::tool_router(),
        }
    }

    // Lightweight health-check tool. Useful for verifying the server is reachable
    // before sending real queries.
    #[tool(description = "Ping the KUKA knowledge server to confirm it is running")]
    fn ping(&self) -> Result<CallToolResult, McpError> {
        Ok(CallToolResult::success(vec![Content::text(
            "KUKA Knowledge server is online and ready.",
        )]))
    }

    #[tool(description = "List all documents in the KUKA knowledge bundle, grouped by type")]
    fn list_docs(&self) -> Result<CallToolResult, McpError> {
        list_docs_in(&knowledge_dir())
    }

    #[tool(description = "Search KUKA robot documentation for a given query")]
    fn search_docs(
        &self,
        Parameters(input): Parameters<SearchInput>,
    ) -> Result<CallToolResult, McpError> {
        Ok(run_search(&knowledge_dir(), &input.query))
    }
}

// The presentation layer for search: runs the engine (search.rs, which returns
// plain SearchHit data) and formats the outcome as an MCP tool result. All
// user-facing wording lives here, none of it in the engine.
fn run_search(dir: &std::path::Path, query: &str) -> CallToolResult {
    let query_lower = query.to_lowercase();
    let terms = parse_query(&query_lower);

    // Guard: all() over an empty term list is vacuously true and would match
    // every document. Return early with a helpful message instead.
    if terms.is_empty() {
        return CallToolResult::success(vec![Content::text(
            "Query contains only common words. Please add specific search terms.".to_string(),
        )]);
    }

    // A missing/unreadable bundle directory is a tool ERROR (isError = true),
    // clearly distinct from "no results found".
    let docs = match load_bundle(dir) {
        Ok(docs) => docs,
        Err(e) => {
            return CallToolResult::error(vec![Content::text(format!(
                "Cannot read knowledge bundle: {e:#}"
            ))]);
        }
    };

    let hits = search(&docs, &terms);

    let text = if hits.is_empty() {
        format!("No results found for '{query}'.")
    } else {
        let ranked: Vec<String> = hits.iter().map(format_hit).collect();
        format!(
            "Found {} result(s) for '{query}':\n\n{}",
            hits.len(),
            ranked.join("\n\n")
        )
    };

    CallToolResult::success(vec![Content::text(text)])
}

// Renders one hit as the bullet-point block shown to the client.
fn format_hit(hit: &SearchHit) -> String {
    format!(
        "• {}\n  Source: {}\n\n  ...{}...",
        hit.title,
        hit.resource,
        hit.excerpts.join("\n\n  ...")
    )
}

// #[tool_handler] wires the tool_router into the ServerHandler trait so the MCP
// framework knows how to dispatch incoming tool calls.
#[tool_handler]
impl ServerHandler for KukaServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(
            ServerCapabilities::builder()
                .enable_tools()
                .enable_resources()
                .build(),
        )
        .with_instructions(
            "KUKA AMR robot knowledge server. \
             Use the ping tool to confirm the server is alive."
                .to_string(),
        )
    }

    async fn list_resources(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListResourcesResult, McpError> {
        // One loader for the whole bundle (bundle.rs). A missing directory is
        // reported as a protocol error instead of silently listing nothing.
        let docs = load_bundle(&knowledge_dir()).map_err(|e| McpError {
            code: ErrorCode::INTERNAL_ERROR,
            message: format!("Cannot read knowledge bundle: {e:#}").into(),
            data: None,
        })?;

        let resources: Vec<Resource> = docs
            .into_iter()
            .map(|doc| {
                let uri = format!("kuka://docs/{}", doc.stem);
                let mut raw = RawResource::new(uri, doc.stem)
                    .with_title(doc.title)
                    .with_mime_type("text/markdown".to_string());
                if let Some(desc) = doc.description {
                    raw = raw.with_description(desc);
                }
                Annotated::new(raw, None)
            })
            .collect();

        Ok(ListResourcesResult::with_all_items(resources))
    }

    async fn read_resource(
        &self,
        request: ReadResourceRequestParams,
        _context: RequestContext<RoleServer>,
    ) -> Result<ReadResourceResult, McpError> {
        let uri = &request.uri;

        // Strip the kuka://docs/ prefix to recover the file stem
        let stem = uri.strip_prefix("kuka://docs/").ok_or_else(|| McpError {
            code: ErrorCode::RESOURCE_NOT_FOUND,
            message: format!("Unknown resource URI: {uri}").into(),
            data: None,
        })?;

        // Path-traversal guard: a stem like "../../secret" would escape the
        // knowledge directory when joined below. Only plain stems are valid.
        if !resource_stem_is_safe(stem) {
            return Err(McpError {
                code: ErrorCode::RESOURCE_NOT_FOUND,
                message: format!("Invalid resource URI: {uri}").into(),
                data: None,
            });
        }

        let path = knowledge_dir().join(format!("{stem}.md"));
        let content = std::fs::read_to_string(&path).map_err(|_| McpError {
            code: ErrorCode::RESOURCE_NOT_FOUND,
            message: format!("Resource not found: {uri}").into(),
            data: None,
        })?;

        Ok(ReadResourceResult::new(vec![ResourceContents::text(
            content,
            uri.clone(),
        )]))
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    // Send tracing output to stderr so it doesn't mix with MCP's stdout messages.
    // Log level is controlled by the RUST_LOG environment variable at runtime.
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::EnvFilter::from_default_env())
        .with_writer(std::io::stderr)
        .with_ansi(false) // disable colour codes (they corrupt MCP's JSON stream)
        .init();

    tracing::info!("Starting KUKA MCP server");

    // Attach the server to stdin/stdout and block until the client disconnects
    let service = KukaServer::new().serve(stdio()).await?;
    service.waiting().await?;
    Ok(())
}

// Tests for the PRESENTATION layer: wording, isError flags, empty-query guard.
// The engine itself is tested in the library (search.rs); these only check
// what this binary adds on top. Note: the library's #[cfg(test)] test_util is
// not visible here — a binary is a separate crate, and the lib it links
// against is compiled without cfg(test) — so this module builds its own fixture.
#[cfg(test)]
mod tool_tests {
    use super::*;
    use std::fs;

    fn bundle_with_one_doc() -> tempfile::TempDir {
        let temp_dir = tempfile::TempDir::new().unwrap();
        let doc = "\
---
type: technical-note
title: Reflector Guide
description: Fixture for tool-layer tests.
resource: kuka-docs/test.pdf
tags: [test]
timestamp: 2026-01-01T00:00:00Z
---

Reflectors must be mounted at a height of 150 to 2000 mm above floor level.";
        fs::write(temp_dir.path().join("reflector-guide.md"), doc).unwrap();
        temp_dir
    }

    // Pulls the text out of a CallToolResult for wording assertions.
    fn result_text(result: &CallToolResult) -> String {
        format!("{:?}", result.content)
    }

    #[test]
    fn search_tool_formats_hits() {
        let temp_dir = bundle_with_one_doc();
        let result = run_search(temp_dir.path(), "reflector height");
        assert_ne!(result.is_error, Some(true));
        let text = result_text(&result);
        assert!(text.contains("Found 1 result(s) for 'reflector height'"));
        assert!(text.contains("Reflector Guide"));
        assert!(text.contains("Source: kuka-docs/test.pdf"));
    }

    #[test]
    fn search_tool_reports_missing_bundle_as_error() {
        let result = run_search(std::path::Path::new("no-such-directory-anywhere"), "reflector");
        assert_eq!(result.is_error, Some(true), "missing dir must set isError");
        assert!(result_text(&result).contains("Cannot read knowledge bundle"));
    }

    #[test]
    fn search_tool_rejects_stop_word_only_query() {
        let temp_dir = bundle_with_one_doc();
        let result = run_search(temp_dir.path(), "what is the");
        assert_ne!(result.is_error, Some(true), "guard message is not an error");
        assert!(result_text(&result).contains("only common words"));
    }

    #[test]
    fn search_tool_reports_no_results() {
        let temp_dir = bundle_with_one_doc();
        let result = run_search(temp_dir.path(), "hydraulic pump");
        assert!(result_text(&result).contains("No results found for 'hydraulic pump'"));
    }
}
